name: Cleanup apps
on:
  pull_request:
    types: [closed]

env:
  HEROKU_APP_NAME: wim-stg-pr-${{ github.event.number }}

jobs: 
  cleanup:
    name: Cleanup Heroku apps
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

    - name: Heroku Login
      run: | 
        cat >~/.netrc <<EOF \
          machine api.heroku.com \
            login ${{secrets.HEROKU_MAIL}} \
          password ${{secrets.HEROKU_API_KEY}} \
          machine git.heroku.com \
            login ${{secrets.HEROKU_MAIL}} \
          password ${{secrets.HEROKU_API_KEY}} \
          EOF`
    - name: Destroy Heroku app
      run: heroku apps:destroy --app=${{ env.HEROKU_APP_NAME }} --confirm=${{ env.HEROKU_APP_NAME }}