name: Cleanup apps
on:
  pull_request:
    types: [closed]

env:
  HEROKU_APP_NAME: wim-stg-pr-${{ github.event.number }}

jobs: 
  cleanup:
    name: Cleanup Heroku apps
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:

    - name: Heroku Login
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_email: ${{ secrets.HEROKU_MAIL }}
        heroku_app_name: ${{ env.HEROKU_APP_NAME }}
        justlogin: true
    - name: Destroy Heroku app
      run: heroku apps:destroy --app=${{ env.HEROKU_APP_NAME }} --confirm=${{ env.HEROKU_APP_NAME }}