name: Deploy on Push

on:
  workflow_dispatch:
    branches: [ "master" ]
  push:
    branches: [ "master" ]

jobs:
  compile:
    name: Maven Compile
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8, 18 ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 
      uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'
        cache: maven
    - name: Maven Compile
      run: mvn -B compile --file pom.xml

  test:
    name: Maven Test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Maven Test
      run: mvn -B test --file pom.xml
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v1
      if: always()
      with:
        files: "target/surefire-reports/**/*.xml"
    - name: Upload JaCoCo coverage report
      uses: actions/upload-artifact@v2
      with:
        name: jacoco-report
        path: target/site/jacoco/
    - name: Generate JaCoCo Badge
      id: jacoco
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
    - name: Log coverage percentage
      run: |
        echo '# Test coverage' >> $GITHUB_STEP_SUMMARY
        echo '${{ steps.jacoco.outputs.coverage }}' | awk '{printf "Test coverage:  %.0f%", $1 * 100}' >> $GITHUB_STEP_SUMMARY
        echo '  ' >> $GITHUB_STEP_SUMMARY
        echo '${{ steps.jacoco.outputs.branches }}' | awk '{printf "Branch coverage: %.0f%", $1 * 100}' >> $GITHUB_STEP_SUMMARY
    - name: Commit and push the badge (if it changed)
      uses: EndBug/add-and-commit@v7
      with:
        default_author: github_actions
        message: 'commit badge'
        add: '*.svg'
      

  package:
    name: Maven Package
    timeout-minutes: 10
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Maven Package
      run: mvn -B package --file pom.xml -Dmaven.test.skip=true      
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: calculator.jar
        path:
          target/calculator.jar
        retention-days: 30

  deploy-staging:
    name: Deploy to Staging
    timeout-minutes: 10
    needs: package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upload to Heroku
        uses: jreker/heroku-deploy-action@v1.5
        with:
          APP_NAME: wim-app-staging
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          MAIL: ${{secrets.HEROKU_MAIL}}
          BRANCH_NAME: ${{ github.head_ref }}

  deploy-production:
    name: Deploy to Production
    timeout-minutes: 10
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Upload to Heroku
        uses: jreker/heroku-deploy-action@v1.5
        with:
          APP_NAME: wim-app-prod
          HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
          MAIL: ${{secrets.HEROKU_MAIL}}
          BRANCH_NAME: ${{ github.head_ref }}